
  CREATE TABLE "BOARD" 
   (  "SEQ" NUMBER(7,0) NOT NULL ENABLE, 
  "TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
  "CONTENTS" CLOB, 
  "READ_CNT" NUMBER(6,0) DEFAULT 0, 
  "REG_DT" DATE DEFAULT SYSDATE, 
  "REG_ID" VARCHAR2(20 BYTE), 
  "MOD_DT" DATE DEFAULT SYSDATE, 
  "MOD_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "PK_BOARD" ON "BOARD" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("SEQ")
  USING INDEX "PK_BOARD"  ENABLE;

   COMMENT ON COLUMN "BOARD"."SEQ" IS '순번';
   COMMENT ON COLUMN "BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "BOARD"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "BOARD"."READ_CNT" IS '조회수';
   COMMENT ON COLUMN "BOARD"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BOARD"."REG_ID" IS '등록자';
   COMMENT ON COLUMN "BOARD"."MOD_DT" IS '수정일';
   COMMENT ON COLUMN "BOARD"."MOD_ID" IS '수정자';
   COMMENT ON TABLE "BOARD"  IS '커뮤니티';