--INSERT INTO table이름 [컬럼1,컬럼2,...]
--VALUES (VALUE1, VALUE2,...)

--테이블 생성
CREATE TABLE DEPT_DML
AS
SELECT *
FROM dept;

SELECT * FROM dept_dml;

--테이블에 데이터 추가
INSERT INTO dept_dml VALUES (50,'DATABASE','SHINCHON');
commit;

--INSERT 문법 오류
INSERT INTO dept_dml(DEPTNO,DNAME,LOC)VALUES (60,'WEB_DEVELOPER','SELUL',1);

INSERT INTO dept_dml(DEPTNO,DNAME,LOC)
VALUES(60,'WEB_DEVELOPER','SEOUL');

ROLLBACK;

--NULL데이터 입력
INSERT INTO dept_dml(DEPTNO,DNAME,LOC)
VALUES (70,'BACKAND DEV',NULL);

