CREATE OR REPLACE TRIGGER TRG_DEPT_LOG
AFTER
INSERT OR UPDATE OR DELETE ON DEPT_TRG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG','INSERT',:NEW.DEPTNO,
            SYS_CONTEXT('USERENV', 'SESSION_USER'),SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG','UPDATE',:OLD.DEPTNO,
            SYS_CONTEXT('USERENV', 'SESSION_USER'),SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO DEPT_TRG_LOG
            VALUES('DEPT_TRG','DELETE',:OLD.DEPTNO,
            SYS_CONTEXT('USERENV', 'SESSION_USER'),SYSDATE);
    END IF;
END;
/
INSERT INTO DEPT_TRG VALUES(99, 'TEST_DNAME', 'SEOUL');
UPDATE DEPT_TRG SET LOC = 'TEST_LOC' WHERE DEPTNO = 99;
DELETE FROM DEPT_TRG WHERE DEPTNO = 99;
SELECT * FROM DEPT_TRG;
SELECT * FROM DEPT_TRG_LOG;