/* 새 테이블 */
DROP TABLE DEPT_TRG_LOG 
	CASCADE CONSTRAINTS;

/* 새 테이블 */
CREATE TABLE DEPT_TRG_LOG (
	TABLENAME VARCHAR2(10), /* 테이블이름 */
	DML_TYPE VARCHAR2(10), /* 명령어종류 */
	DEPTNO NUMBER(2), /* 부서번호 */
	USER_NAME VARCHAR2(30), /* 유저이름 */
	CHANGE_DATE DATE /* 수행날짜 */
);

COMMENT ON TABLE DEPT_TRG_LOG IS '새 테이블';

COMMENT ON COLUMN DEPT_TRG_LOG.TABLENAME IS '테이블이름';

COMMENT ON COLUMN DEPT_TRG_LOG.DML_TYPE IS '명령어종류';

COMMENT ON COLUMN DEPT_TRG_LOG.DEPTNO IS '부서번호';

COMMENT ON COLUMN DEPT_TRG_LOG.USER_NAME IS '유저이름';

COMMENT ON COLUMN DEPT_TRG_LOG.CHANGE_DATE IS '수행날짜';