CREATE OR REPLACE FUNCTION func_date_kor
(
    IN_DATA IN EMP.HIREDATE%TYPE

)
RETURN VARCHAR2
IS
    KOR_DATA VARCHAR2(30);

BEGIN
    KOR_DATA := TO_CHAR(IN_DATA,'YYYY"³â"MM"¿ù"DD"ÀÏ"');
    RETURN KOR_DATA;
END;
/

SELECT ENAME,func_date_kor(HIREDATE) AS HIREDATE
FROM EMP
WHERE EMPNO = 7369;