SELECT T1.TABLE_NAME,
       T1.COLUMN_NAME,
       T1.INDEX_NAME
FROM USER_IND_COLUMNS T1
WHERE T1.TABLE_NAME = 'DEPT2';

SELECT t1.table_name,
       t1.index_name
FROM USER_INDEXES T1
WHERE T1.TABLE_NAME = 'DEPT2';