DROP INDEX PK_CMN_CODE;

/* 공통 코드 */
DROP TABLE CMN_CODE 
	CASCADE CONSTRAINTS;

/* 공통 코드 */
CREATE TABLE CMN_CODE (
	MST_CODE VARCHAR2(30) NOT NULL,
	DET_CODE VARCHAR2(30) NOT NULL,
	MST_NAME VARCHAR2(50  CHAR),
	DET_NAME VARCHAR2(50 CHAR),
	SEQ NUMBER,
	USE_YN CHAR(1 BYTE) DEFAULT '1',
	REG_DT DATE DEFAULT SYSDATE,
	REG_ID VARCHAR2(20),
	MOD_DT DATE DEFAULT SYSDATE,
	MOD_ID VARCHAR2(20)
);

COMMENT ON TABLE CMN_CODE IS '공통 코드';

COMMENT ON COLUMN CMN_CODE.MST_CODE IS '마스터코드';

COMMENT ON COLUMN CMN_CODE.DET_CODE IS '디테일코드';

COMMENT ON COLUMN CMN_CODE.MST_NAME IS '마스터명';

COMMENT ON COLUMN CMN_CODE.DET_NAME IS '디테일명';

COMMENT ON COLUMN CMN_CODE.SEQ IS '순서';

COMMENT ON COLUMN CMN_CODE.USE_YN IS '사용여부';

COMMENT ON COLUMN CMN_CODE.REG_DT IS '등록일';

COMMENT ON COLUMN CMN_CODE.REG_ID IS '등록자';

COMMENT ON COLUMN CMN_CODE.MOD_DT IS '수정일';

COMMENT ON COLUMN CMN_CODE.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_CMN_CODE
	ON CMN_CODE (
		MST_CODE ASC,
		DET_CODE ASC
	);

ALTER TABLE CMN_CODE
	ADD
		CONSTRAINT PK_CMN_CODE
		PRIMARY KEY (
			MST_CODE,
			DET_CODE
		);