-- 테이블 생성
CREATE TABLE MEMBER(
USER_ID VARCHAR2 (20),
PASSWD VARCHAR2 (20),
NAME VARCHAR2 (30),
EMAIL VARCHAR2 (320),
BIRTH CHAR (8),
CELLPHONE VARCHAR2(13),
RANKING VARCHAR2(2),
REG_DT DATE,
REG_ID VARCHAR2 (20),
MOD_DT DATE,
MOD_ID VARCHAR2 (20)
);
