CREATE TABLE PC_BOARD (
        SEQ NUMBER(7) NOT NULL,
        TITLE VARCHAR2(200) NOT NULL,
        CONTENTS CLOB,
        READ_CNT NUMBER(6) DEFAULT 0,
        REG_DT DATE DEFAULT SYSDATE,
        REG_ID VARCHAR2(20),
        MOD_DT DATE DEFAULT SYSDATE,
        MOD_ID VARCHAR2(20)
);
COMMENT ON TABLE BOARD IS '커뮤니티';
COMMENT ON COLUMN BOARD.SEQ IS '순번';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENTS IS '내용';
COMMENT ON COLUMN BOARD.READ_CNT IS '조회수';
COMMENT ON COLUMN BOARD.REG_DT IS '등록일';
COMMENT ON COLUMN BOARD.REG_ID IS '등록자';
COMMENT ON COLUMN BOARD.MOD_DT IS '수정일';
COMMENT ON COLUMN BOARD.MOD_ID IS '수정자';
CREATE UNIQUE INDEX PK_BOARD
        ON PC_BOARD (
                SEQ ASC
        );
ALTER TABLE PC_BOARD
        ADD
                CONSTRAINT PK_PC_BOARD
                PRIMARY KEY (
                        SEQ
                );
