CREATE SEQUENCE t_seq
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE TABLE T_SEQ_TEST
(
NO NUMBER DEFAULT T_SEQ.NEXTVAL PRIMARY KEY,
NAME VARCHAR2(20)
);

BEGIN
    FOR I IN 1..10 LOOP
        INSERT INTO T_SEQ_TEST(NAME)
        VALUES (DBMS_RANDOM.STRING('a',10));
    END LOOP;
    COMMIT;
END;
/

SELECT * FROM T_SEQ_TEST;