SELECT tablespace_name,
       file_name
FROM dba_data_files
;

CREATE TABLESPACE jci_ts
DATAFILE 'C:\APP\ITSC\PRODUCT\21C\ORADATA\XE\jci01.DBF'
SIZE 200M AUTOEXTEND ON next 20M;

ALTER SESSION SET "_oracle_script"=true;

CREATE USER jci
IDENTIFIED BY pcwk
DEFAULT TABLESPACE JCI_TS
TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION TO jci;
GRANT RESOURCE, CREATE TABLE TO jci;
ALTER USER jci DEFAULT TABLESPACE jci_ts QUOTA UNLIMITED ON jci_ts;