  DROP TABLE HR_MEMBER;
  CREATE TABLE HR_MEMBER 
   ( U_ID       VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 NAME       VARCHAR2(50 CHAR), 
	 PASSWD     VARCHAR2(50 BYTE), 
     U_LEVEL	NUMBER(2),
     LOGIN	    NUMBER(8),
     RECOMMEND	NUMBER(8),
     EMAIL		VARCHAR2(320),
     REG_DT		DATE DEFAULT SYSDATE,
	 CONSTRAINT PK_HR_MEMBER PRIMARY KEY (U_ID)
   ) ;
  
  DESC HR_MEMBER;