SELECT SYSDATE,
       TO_CHAR(SYSDATE, 'MONTH','NLS_DATE_LANGUAGE=ENGLISH') "ENGLISH",
       TO_CHAR(SYSDATE, 'MON','NLS_DATE_LANGUAGE=ENGLISH') "ENGLISH_MON",
       TO_CHAR(SYSDATE, 'MON','NLS_DATE_LANGUAGE=KOREAN') "KOREAN",
       TO_CHAR(SYSDATE, 'MON','NLS_DATE_LANGUAGE=JAPANESE') "JAPANESE"
FROM dual
;